### ISSUE TITLE
"Cannot find a version of 'androidx.browser:browser' that satisfies the version constraints" when building android app

### ISSUE THREAD

**Issue by luckyhandler** [droibit/flutter_custom_tabs#136] opened 2023-11-07 18:25 UTC
I integrated `flutter_custom_tabs: 2.0.0-beta` into my `pubspec.yaml`. When building for Android I get 

```
> Could not resolve all files for configuration ':app:appdevReleaseCompileClasspath'.
   > Could not resolve androidx.browser:browser:{strictly 1.5.0}.
     Required by:
         project :app > project :flutter_custom_tabs_android
      > Cannot find a version of 'androidx.browser:browser' that satisfies the version constraints:
           Dependency path 'android:app:unspecified' --> 'com.github.droibit.plugins.flutter.customtabs:flutter_custom_tabs_android:1.0-SNAPSHOT' (releaseApiElements) --> 'androidx.browser:browser:{strictly 1.5.0}'
           Dependency path 'android:app:unspecified' --> 'com.github.droibit.plugins.flutter.customtabs:flutter_custom_tabs_android:1.0-SNAPSHOT' (releaseApiElements) --> 'com.github.droibit:customtabslauncher:2.0.0-beta01' (releaseApiElements-published) --> 'androidx.browser:browser:1.6.0'

   > Could not resolve androidx.browser:browser:1.6.0.
     Required by:
         project :app > com.github.droibit:customtabslauncher:2.0.0-beta01
      > Cannot find a version of 'androidx.browser:browser' that satisfies the version constraints:
           Dependency path 'android:app:unspecified' --> 'com.github.droibit.plugins.flutter.customtabs:flutter_custom_tabs_android:1.0-SNAPSHOT' (releaseApiElements) --> 'androidx.browser:browser:{strictly 1.5.0}'
           Dependency path 'android:app:unspecified' --> 'com.github.droibit.plugins.flutter.customtabs:flutter_custom_tabs_android:1.0-SNAPSHOT' (releaseApiElements) --> 'com.github.droibit:customtabslauncher:2.0.0-beta01' (releaseApiElements-published) --> 'androidx.browser:browser:1.6.0'
```

`flutter doctor` output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.4)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
    ! Device emulator-5562 is offline.
[✓] Network resources

• No issues found!

```

**Comment by luckyhandler** [comment] 2023-11-07 18:45
Adding 

```gradle
configurations.all {
    resolutionStrategy { force 'androidx.browser:browser:1.6.0' }
}
```

to my app's `build.gradle` solves this though.

**Comment by droibit** [comment] 2023-11-08 12:47
Hi @luckyhandler ,

Thanks for your report on the 2.0.0-beta version of `flutter_custom_tabs`.

I created a minimal sample that depends on`flutter_custom_tabs`, but I can't reproduce the issue in my environment.   
- https://github.com/droibit/flutter_custom_tabs_playground

Here is the `flutter doctor` output from my environment:

```
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.4)
[✓] VS Code (version 1.84.1)
[✓] Connected device (2 available)
[✓] Network resources
```

Could you provide a minimal sample project to reproduce this build error?

**Comment by droibit** [comment] 2023-11-08 15:07
Thank you for providing the sample.

I have found that the version conflict of the `androidx.browser` library, which the following package plugins internally depend on, is causing the build error.

* `flutter_custom_tabs`
* `flutter_inappwebview`

Please wait for the fixed version of the `flutter_custom_tabs_android` package plugin, which will be released soon.

**Comment by luckyhandler** [comment] 2023-11-08 15:25
Can the mentioned fix cause any problems with your library?

**Comment by droibit** [comment] 2023-11-09 12:21
I don't think it will cause any problems.  

I've just published the fixed version `flutter_custom_tabs_android` v2.0.0-beta+1 to pub.dev.
- https://pub.dev/packages/flutter_custom_tabs_android/versions/2.0.0-beta+1

Could you please run the `flutter pub upgrade` command to update `flutter_custom_tabs` and check if the build error is resolved?

**Comment by luckyhandler** [comment] 2023-11-09 12:56
By replacing ` flutter_custom_tabs: 2.0.0-beta` with `flutter_custom_tabs_android: 2.0.0-beta+1` there's another issue coming up:

```
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 2 issues were found when checking AAR metadata:

       1.  Dependency 'androidx.webkit:webkit:1.8.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.0 is 33.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

       2.  Dependency 'androidx.browser:browser:1.6.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.0 is 33.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
```

**Comment by luckyhandler** [comment] 2023-11-09 13:04
I will test on the same phone later... Having different issues on a different phone...

**Comment by droibit** [comment] 2023-11-09 13:23
If you're getting a build error requiring `compileSdkVersion = 34`, you can fix it by changing the configuration in your Android app's `build.gradle` to the following:

```diff
 // android/app/build.gradle
 android {
-   compileSdkVersion flutter.compileSdkVersion // or 33
+   compileSdkVersion 34
 }
```

This error is not caused by `flutter_custom_tabs`, but by other plugin packages that depend on Android libraries that require `compileSdkVersion = 34`.

For example:  
```yaml
flutter_inappwebview: ^6.0.0-beta.25
```

**Comment by droibit** [comment] 2023-11-18 05:15
I'm closing this issue for now, but please reopen it if the build error is not resolved.

**Closed by droibit** 2023-11-18 05:15 UTC
