### ISSUE TITLE
Warmup browser

### ISSUE THREAD

**Issue by ymmooot** [droibit/flutter_custom_tabs#175] opened 2024-01-17 09:49 UTC
There is a `warmup` API on CustomTabsClient.
https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsClient#warmup(long)

Do you have any plan to implement it to be able to call it from flutter?

**Comment by droibit** [comment] 2024-01-24 11:15
Thank you for the feedback.

I do not have any plans to implement the `warmup` API at this time,   
but I will consider supporting it after the stable release of v2.0.0.

**Comment by Satendra9984** [comment] 2024-10-23 06:51
Yes it will be a good feature as prefetching the urls is needed for seamless experience. Can you tell me if prefetching is already implemented as I need it as the warmup session is maintained until the app is open ?
In my app I need preload of previously visited urls so that next time it is faster and snappy.
Please tell any approach for this.

**Comment by droibit** [comment] 2024-11-05 11:22
Closing this issue as it is a duplicate of #210 .   
Please continue the discussion there.

**Closed by droibit** 2024-11-05 11:22 UTC
